#positon
float64 x
float64 y
float64 z

#orentation
float64 qx
float64 qy
float64 qz
float64 qw

float64 heading

#velocity,forward/left/up meters per second in car frame
float64 vx
float64 vy
float64 vz
#velocity,forward/left/up meters per second in enu frame
float64 ve
float64 vn
float64 vu

#acceration,Right/forward/up in meters per square second.
float64 ax
float64 ay
float64 az
#Angular velocity of the VRP in the vehicle reference frame.
#Around right/forward/up axes in radians per second.
float64 avx
float64 avy
float64 avz




